---
abstract: 'A POE::Component::IRC plugin that talks bollocks.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.84'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-Bollocks
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Dev::Bollocks: 0.06
  POE: 1.004
  POE::Component::IRC: 5.68
  POE::Component::IRC::Plugin: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-irc-plugin-bollocks.git
version: 1.00
